### ISSUE TITLE
Touchscreen changes

### ISSUE THREAD

**Issue by jakibaki** [TobleMiner/wintron7.0#1]
The method of installing the touchscreen driver has changed and it is now calibrated by default and multitouch is working great :)

**Comment by TobleMiner** [comment]
That sounds great! I'll do some testing in the next days and update the provided information.

**Comment by TobleMiner** [comment]
Mh, I guess "next days" is pretty much over now (sorry!) but on the bright side there is now a silead driver in linux that is compatible with this tablet. Documentation has been updated
