### ISSUE TITLE
NMI watchdog: Watchdog detected hard LOCKUP on cpu X

### ISSUE THREAD

**Issue by hellerbarde** [TobleMiner/wintron7.0#2]
I got the kernel messages mentioned in the title whenever I make the CPU do some work. 

Did you see these messages too? and does anyone know what they mean and whether they are a problem?

Example:

```
NMI watchdog: Watchdog detected hard LOCKUP on cpu 0
NMI watchdog: Watchdog detected hard LOCKUP on cpu 1
NMI watchdog: Watchdog detected hard LOCKUP on cpu 0
NMI watchdog: Watchdog detected hard LOCKUP on cpu 3
NMI watchdog: Watchdog detected hard LOCKUP on cpu 2
```

They are each a few seconds apart (1-20 seconds apart)

PS: I'm not expecting you to solve this for me, I just haven't really found a "community" for this baytrail stuff yet.

**Comment by hellerbarde** [comment]
Here is a pic
![hard_lockup_wintron](https://cloud.githubusercontent.com/assets/37417/14764625/db363ab8-09be-11e6-88bd-8187b2593060.jpg)

**Comment by Manawyrm** [comment]
Interesting... I haven't had this happen, even when compiling stuff with make -j5... 

Have you fiddled around with the clocksource settings in the kernel parameters?

**Comment by hellerbarde** [comment]
Actually, a friend just mentioned the clocksource=tsc. No, I hadn't tried it yet. I'm trying to look up what it does.
Thanks. I'll be back with my findings :+1:

**Comment by Manawyrm** [comment]
We have had issues with the clock running to fast (like 30 minutes in 10 real minutes), that was fixed with the clocksource-setting.

**Comment by hellerbarde** [comment]
I have been running my stress tests now for a few minutes. Longer than it took last time to crash the tablet completely. No messages so far. I'm gonna close this now. If it turns up again, it will probably be a different issue :+1: Thanks!

EDIT: I added the clocksource=tsc to fix it, as suggested.
